apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"qos-orchestrator"},"name":"qos-orchestrator","namespace":"orchestrator"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"qos-orchestrator"}},"template":{"metadata":{"labels":{"app":"qos-orchestrator"}},"spec":{"containers":[{"image":"192.168.49.174:5000/qos-orchestrator:v7","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/health","port":9200},"initialDelaySeconds":10,"periodSeconds":30},"name":"orchestrator","ports":[{"containerPort":9200,"hostPort":9200,"name":"metrics"}],"readinessProbe":{"httpGet":{"path":"/health","port":9200},"initialDelaySeconds":5,"periodSeconds":10},"resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"securityContext":{"capabilities":{"add":["NET_ADMIN"]}},"volumeMounts":[{"mountPath":"/root/.ssh","name":"ssh-keys","readOnly":true}]}],"hostNetwork":true,"nodeSelector":{"role":"control"},"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/control-plane","operator":"Exists"}],"volumes":[{"hostPath":{"path":"/home/kube-master/.ssh","type":"Directory"},"name":"ssh-keys"}]}}}}
    creationTimestamp: "2026-04-29T11:32:29Z"
    generation: 2
    labels:
      app: qos-orchestrator
    name: qos-orchestrator
    namespace: orchestrator
    resourceVersion: "2562283"
    uid: 5afb6749-c654-4d9d-bdcb-a8745e1e8efc
  spec:
    progressDeadlineSeconds: 600
    replicas: 0
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: qos-orchestrator
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: qos-orchestrator
      spec:
        containers:
        - image: 192.168.49.174:5000/qos-orchestrator:v7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9200
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: orchestrator
          ports:
          - containerPort: 9200
            hostPort: 9200
            name: metrics
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9200
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /root/.ssh
            name: ssh-keys
            readOnly: true
        dnsPolicy: ClusterFirst
        hostNetwork: true
        nodeSelector:
          role: control
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        volumes:
        - hostPath:
            path: /home/kube-master/.ssh
            type: Directory
          name: ssh-keys
  status:
    conditions:
    - lastTransitionTime: "2026-04-29T11:32:29Z"
      lastUpdateTime: "2026-04-29T11:32:39Z"
      message: ReplicaSet "qos-orchestrator-8ff59c567" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-05-01T15:09:49Z"
      lastUpdateTime: "2026-05-01T15:09:49Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 2
kind: List
metadata:
  resourceVersion: ""
