apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"slice":"default"},"name":"default-app","namespace":"default-slice"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"name":"http","nodePort":30800,"port":80,"targetPort":80}],"selector":{"app":"default-app"},"type":"NodePort"}}
    creationTimestamp: "2026-05-03T09:50:18Z"
    labels:
      slice: default
    name: default-app
    namespace: default-slice
    resourceVersion: "2793936"
    uid: 81fffa79-00a9-43ca-9c9c-90dc15b31d81
  spec:
    clusterIP: 10.106.200.147
    clusterIPs:
    - 10.106.200.147
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30800
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: default-app
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
