apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"influxdb","namespace":"mmtc"},"spec":{"ports":[{"name":"http","nodePort":30886,"port":8086,"targetPort":8086}],"selector":{"app":"influxdb"},"type":"NodePort"}}
    creationTimestamp: "2026-05-01T08:00:17Z"
    name: influxdb
    namespace: mmtc
    resourceVersion: "2521749"
    uid: d0f30672-1256-408b-bfe6-76e86b6a4219
  spec:
    clusterIP: 10.111.12.180
    clusterIPs:
    - 10.111.12.180
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30886
      port: 8086
      protocol: TCP
      targetPort: 8086
    selector:
      app: influxdb
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mmtc-app","slice":"mmtc"},"name":"mmtc-app","namespace":"mmtc"},"spec":{"ports":[{"name":"mqtt","nodePort":30883,"port":1883,"targetPort":1883},{"name":"mqtt-ws","nodePort":30901,"port":9001,"targetPort":9001}],"selector":{"app":"mmtc-app"},"type":"NodePort"}}
    creationTimestamp: "2026-04-12T07:10:13Z"
    labels:
      app: mmtc-app
      slice: mmtc
    name: mmtc-app
    namespace: mmtc
    resourceVersion: "2521726"
    uid: 83af5849-5698-43c5-b03d-3fdc0423f557
  spec:
    clusterIP: 10.99.208.6
    clusterIPs:
    - 10.99.208.6
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: mqtt
      nodePort: 30883
      port: 1883
      protocol: TCP
      targetPort: 1883
    - name: mqtt-ws
      nodePort: 30901
      port: 9001
      protocol: TCP
      targetPort: 9001
    selector:
      app: mmtc-app
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mmtc-nodered","namespace":"mmtc"},"spec":{"ports":[{"name":"http","nodePort":30881,"port":1880,"targetPort":1880}],"selector":{"app":"mmtc-nodered"},"type":"NodePort"}}
    creationTimestamp: "2026-05-01T08:00:17Z"
    name: mmtc-nodered
    namespace: mmtc
    resourceVersion: "2521739"
    uid: 65fad08b-eefe-462c-a6e6-5b442ba7d026
  spec:
    clusterIP: 10.102.240.50
    clusterIPs:
    - 10.102.240.50
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 30881
      port: 1880
      protocol: TCP
      targetPort: 1880
    selector:
      app: mmtc-nodered
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"upf-mmtc","slice":"mmtc"},"name":"upf-mmtc-metrics","namespace":"mmtc"},"spec":{"ports":[{"name":"metrics","port":9092,"targetPort":9092}],"selector":{"app":"upf-mmtc"},"type":"ClusterIP"}}
    creationTimestamp: "2026-04-12T06:41:36Z"
    labels:
      app: upf-mmtc
      slice: mmtc
    name: upf-mmtc-metrics
    namespace: mmtc
    resourceVersion: "4657"
    uid: be7e0030-e8a5-4dff-8648-131efe2447f5
  spec:
    clusterIP: 10.101.77.219
    clusterIPs:
    - 10.101.77.219
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: metrics
      port: 9092
      protocol: TCP
      targetPort: 9092
    selector:
      app: upf-mmtc
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
