apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"priority":"0","slice":"default"},"name":"default-slice"}}
  creationTimestamp: "2026-05-02T11:37:18Z"
  labels:
    kubernetes.io/metadata.name: default-slice
    priority: "0"
    slice: default
  name: default-slice
  resourceVersion: "2673278"
  uid: 6dc9a316-8347-4ca4-ab0e-578d0358a2f6
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
