apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-04-12T05:55:01Z"
  labels:
    kubernetes.io/metadata.name: default
  name: default
  resourceVersion: "19"
  uid: 7bffde53-d5c3-4e06-a185-aeb97775a932
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
