apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"purpose":"observability"},"name":"monitoring"}}
  creationTimestamp: "2026-04-12T06:41:34Z"
  labels:
    kubernetes.io/metadata.name: monitoring
    purpose: observability
  name: monitoring
  resourceVersion: "4692"
  uid: b92cd71b-3177-4bd9-9921-3482cba87f76
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
